tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "sidneys/homebrew"
brew "gettext"
brew "aria2"
brew "bat"
brew "bitwarden-cli"
brew "cabextract"
brew "coreutils"
brew "cask"
brew "cdrtools"
brew "cheat"
brew "chezmoi"
brew "cowsay"
brew "difftastic"
brew "docker"
brew "sdl2"
brew "ffmpeg"
brew "font-util"
brew "git"
brew "gitui"
brew "python@3.11"
brew "glances"
brew "libgpg-error"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "mas"
brew "micro"
brew "midnight-commander"
brew "nano"
brew "ncdu"
brew "ncspot"
brew "neofetch"
brew "newsboat"
brew "pandoc"
brew "pdfgrep"
brew "pinentry-mac"
brew "zsh-async"
brew "pure"
brew "python@3.10"
brew "qalculate-gtk"
brew "rclone"
brew "restic"
brew "sl"
brew "spark"
brew "sqlite-utils"
brew "subversion"
brew "task"
brew "telnet"
brew "tig"
brew "tree"
brew "wakeonlan"
brew "wget"
brew "wimlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "sidneys/homebrew/chntpw"
cask "airbuddy"
cask "alt-tab"
cask "appcleaner"
cask "applite"
cask "arc"
cask "audacity"
cask "audio-hijack"
cask "balenaetcher"
cask "bartender"
cask "bettertouchtool"
cask "calibre"
cask "camo-studio"
cask "cheatsheet"
cask "coconutbattery"
cask "cyberduck"
cask "daisydisk"
cask "db-browser-for-sqlite"
cask "discord"
cask "docker"
cask "firefox"
cask "fliqlo"
cask "font-barlow"
cask "font-commit-mono"
cask "font-ibm-plex-mono"
cask "font-inter"
cask "font-iosevka-ss14"
cask "font-jetbrains-mono"
cask "font-merriweather"
cask "font-national-park"
cask "font-sf-compact"
cask "font-sf-mono"
cask "font-sf-pro"
cask "gimp"
cask "github"
cask "gitx"
cask "google-chrome"
cask "handbrake"
cask "hyper"
cask "iina"
cask "imazing"
cask "itsycal"
cask "keepassxc"
cask "keka"
cask "keyboardcleantool"
cask "kindle"
cask "macupdater"
cask "marta"
cask "meld"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-remote-desktop"
cask "minecraft"
cask "miniwol"
cask "monitorcontrol"
cask "mono-mdk-for-visual-studio"
cask "mos"
cask "netnewswire"
cask "notion"
cask "numi"
cask "obs"
cask "obsidian"
cask "onedrive"
cask "pika"
cask "pinta"
cask "qlmarkdown"
cask "raindropio"
cask "raycast"
cask "readdle-spark"
cask "rectangle"
cask "rocket"
cask "shottr"
cask "signal"
cask "sloth"
cask "soulver"
cask "spotify"
cask "stats"
cask "steam"
cask "sublime-text"
cask "tailscale"
cask "the-unarchiver"
cask "transmission"
cask "ukelele"
cask "utm"
cask "viber"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "wacom-tablet"
cask "warp"
cask "zoom"
mas "1Blocker", id: 1365531024
mas "Apple Configurator", id: 1037126344
mas "Bitwarden", id: 1352778147
mas "Detail", id: 6443923358
mas "Dropover", id: 1355679052
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Photomator", id: 1444636541
mas "Pixelmator Pro", id: 1289583905
mas "Spark", id: 1176895641
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "UpNote", id: 1398373917
mas "Xcode", id: 497799835
vscode "keesschollaart.vscode-home-assistant"
vscode "PKief.material-icon-theme"
